config/routes.rb
Rails.application.routes.draw do
  resources :donations
  resources :payment_notifications
  devise_for :users
  resources :homes, path: "home"
  resources :users, path: "grs"
  root to: 'homes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/payment_notification.rb
class PaymentNotification < ApplicationRecord
	belongs_to :user
	serialize :params
	after_create :mark_payment_complete

	private
	def mark_payment_complete
		if status == "Completed"
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_coin_payments
  extend FriendlyId
  friendly_id :email, use: :slugged
  	
  	def should_generate_new_friendly_id?
  		new_record? || slug.blank?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
		    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
		    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password, :barcode, :grsaddress])

        end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:amount, :address, :message, :currency, :user_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :body, :user_id)
    end
end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
  before_action :set_payment_notification, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:create]

  # GET /payment_notifications
  # GET /payment_notifications.json
  def index
    @payment_notifications = PaymentNotification.all
  end

  # GET /payment_notifications/1
  # GET /payment_notifications/1.json
  def show
  end

  # GET /payment_notifications/new
  def new
    @payment_notification = PaymentNotification.new
  end

  # GET /payment_notifications/1/edit
  def edit
  end

  # POST /payment_notifications
  # POST /payment_notifications.json
  def create
  PaymentNotification.create!(:params => params, :user_id, :status, :tx_id)    
  end
  end

  # PATCH/PUT /payment_notifications/1
  # PATCH/PUT /payment_notifications/1.json
  def update
    respond_to do |format|
      if @payment_notification.update(payment_notification_params)
        format.html { redirect_to @payment_notification, notice: 'Payment notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_notification }
      else
        format.html { render :edit }
        format.json { render json: @payment_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_notifications/1
  # DELETE /payment_notifications/1.json
  def destroy
    @payment_notification.destroy
    respond_to do |format|
      format.html { redirect_to payment_notifications_url, notice: 'Payment notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_notification
      @payment_notification = PaymentNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_notification_params
      params.require(:payment_notification).permit(:params, :status, :tx_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#before_filter :authenticate_user!
	def index 
		@users = User.all 
		
	end
	
	def create_payment(amount_in_cents)
	  self.coin_payments.create!(reason: 'sale', price: amount_in_cents, coin_type: :btc)
	end

	def show
		# @streamlabs_apiurl = HTTParty.get('https://streamlabs.com/api/v1.0/alerts/send_test_alert?access_token=93E1178689AEC78FFE68&type=donations')
		# @streamlabs_response = @streamlabs_apiurl
		

		#@user = User.find(params[:id])
		@user = User.friendly.find(params[:id])
		respond_to do |format|
	    	format.html # show.html.erb
	    	format.xml { render :xml => @user }
		end


	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donations/_form.html.erb
<%= simple_form_for(@donation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :amount %>
    <%= f.input :address %>
    <%= f.input :message %>
    <%= f.input :currency %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donations</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Address</th>
      <th>Message</th>
      <th>Currency</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.amount %></td>
        <td><%= donation.address %></td>
        <td><%= donation.message %></td>
        <td><%= donation.currency %></td>
        <td><%= donation.user_id %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @donation.amount %>
</p>

<p>
  <strong>Address:</strong>
  <%= @donation.address %>
</p>

<p>
  <strong>Message:</strong>
  <%= @donation.message %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @donation.currency %>
</p>

<p>
  <strong>User:</strong>
  <%= @donation.user_id %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :home_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :home_body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :home_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.title %></td>
        <td><%= home.body %></td>
        <td><%= home.user_id %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @home.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @home.user_id %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/_login.html.erb
<% if user_signed_in? %>
  <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'My Profile', current_user %></li>
            <li role="separator" class="divider"></li>
            <li>
            	<%= link_to(destroy_user_session_path, method: :delete) do %>
  					<i class="glyphicon glyphicon-log-out"></i> Logout
				<% end %>
			</li>
          </ul>
        </li>
  <% else %>
  <li>
  	<%= link_to(new_user_session_path) do %>
			<i class="glyphicon glyphicon-log-in"></i> Login
	<% end %>
  </li>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Gronate', '/', class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= render 'layouts/nav_links' %>
      </ul>
        <%# render 'layouts/search' %>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/register' %>
  		<%= render 'layouts/login' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_links.html.erb
        <li><%= link_to 'Home', '/' %></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->

app/views/layouts/_register.html.erb
<% if user_signed_in? %>
  <li>
  	<%= link_to(edit_user_registration_path) do %>
  		<i class="glyphicon glyphicon-user"></i> Edit Profile
	<% end %>
  </li>
<% else %>
  <li>
  	<%= link_to(new_user_registration_path) do %>
  		<i class="glyphicon glyphicon-user"></i> Register
	<% end %>
  </li>
<% end %>

app/views/layouts/_search.html.erb
<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gronate</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', :debug => false %>
	<%= javascript_include_tag 'application', :debug => false %>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Gronate | Show your support for your favorite streamers!">
	<meta name="keywords" content="twitch,stream,streaming,streamlabs,donation,donations,tips,bits,notifications,otherobnoxiouskeywords">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet"> 
  </head>

  <body>
  	<div class="container-fluid toppad">
	  	<%= render 'layouts/nav' %>
	    <%= yield %>	
  	</div>
  </body>
</html>

app/views/payment_notifications/_form.html.erb
<%= simple_form_for(@payment_notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :params %>
    <%= f.input :status %>
    <%= f.input :tx_id %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payment_notifications/edit.html.erb
<h1>Editing Payment Notification</h1>

<%= render 'form', payment_notification: @payment_notification %>

<%= link_to 'Show', @payment_notification %> |
<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Params</th>
      <th>Status</th>
      <th>Tx</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_notifications.each do |payment_notification| %>
      <tr>
        <td><%= payment_notification.params %></td>
        <td><%= payment_notification.status %></td>
        <td><%= payment_notification.tx_id %></td>
        <td><%= payment_notification.user_id %></td>
        <td><%= link_to 'Show', payment_notification %></td>
        <td><%= link_to 'Edit', edit_payment_notification_path(payment_notification) %></td>
        <td><%= link_to 'Destroy', payment_notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Notification', new_payment_notification_path %>

app/views/payment_notifications/new.html.erb
<h1>New Payment Notification</h1>

<%= render 'form', payment_notification: @payment_notification %>

<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Params:</strong>
  <%= @payment_notification.params %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment_notification.status %>
</p>

<p>
  <strong>Tx:</strong>
  <%= @payment_notification.tx_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @payment_notification.user_id %>
</p>

<%= link_to 'Edit', edit_payment_notification_path(@payment_notification) %> |
<%= link_to 'Back', payment_notifications_path %>

app/views/users/index.html.erb
<h3>ALL USERS (ADMIN ONLY)</h3>
<div class="col-md-4">
	User	
</div>
<div class="col-md-4">
	Url
</div>
<div class="col-md-4">
	Action
</div>

<% @users.each do |user| %>
<div class="col-md-4">
	<%= user.email %>
</div>
<div class="col-md-4">
	<%= link_to @user_path, user %>
</div>
<div class="col-md-4">
	Ban | Delete | Role
</div>
<% end %>

app/views/users/show.html.erb

<% if current_user == @user && user_signed_in? %>
	<div class="jumbotron">
		<h2>Your Profile Preview</h2>
	</div>
	<div class="col-md-9">
		Your Gronation URL:

		<div class="form-control">

			<%= link_to 'http://gronate.com' + user_path, @user %>
		</div>
		

	</div>
	<div class="col-md-3">
		<div class="form-control"></div>
	</div>
	<div class="col-md-12">
	<hr>

	</div>
	<div class="col-md-9">
		<form action="https://www.paypal.com/cgi-bin/webscr" method="post">

    <!-- Identify your business so that you can collect the payments. -->
    <input type="hidden" name="business" value="<%= @user.email %>" class="form-control" readonly>

    <!-- Specify a Donate button. -->
    <input type="hidden" name="cmd" value="_donations">

    <!-- Specify details about the contribution -->
	Your Twitch Username:
	<% if user_signed_in? %>
			<div class="">
			<input type="" name="item_name" value="<%= current_user.email %>" class="form-control">
			</div>
		<% else %>
			<div>
	    <input type="" name="item_name" value="Enter YOUR twitch Username (optional)" class="form-control">
			</div>
		<% end %>
	Tip Message:
    <input type="" name="item_number" value="Short message to streamer (optional)" class="form-control">
    Amount:
    <input type="" name="amount" value="1.00" class="form-control">
    <input type="" name="currency_code" value="USD" class="form-control">
	<!-- <input name="notify_url" value="http://localhost:3000/status" type="">-->
    <!-- Display the payment button. -->
    <input type="image" name="submit"
    src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif"
    alt="Donate" disabled="">
    <img alt="" width="1" height="1"
    src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >

</form>
	</div>
	<div class="col-md-3">
		<div>
			
			<div>
				Barcode:
				<div class="form-control">
					<%= @user.barcode %>
				</div>
				GRS Address:
				<div class="form-control">
					<%= @user.grsaddress %>
				</div>
			</div>

		</div>
	</div>
		
	<% else %>
		<div class="jumbotron">
		<h2>Tip <%= link_to @user.email, @user, class: 'caps' %> with Groestlcoin!</h2>
	</div>
	<div class="col-md-9">
		<form action="https://www.paypal.com/cgi-bin/webscr" method="post">

    <!-- Identify your business so that you can collect the payments. -->
    <input type="hidden" name="business" value="<%= @user.email %>" class="form-control" readonly>

    <!-- Specify a Donate button. -->
    <input type="hidden" name="cmd" value="_donations">

    <!-- Specify details about the contribution -->
	Your Twitch Username:
	<% if user_signed_in? %>
			<div class="">
			<input type="" name="item_name" value="<%= current_user.email %>" class="form-control">
			</div>
		<% else %>
			<div>
	    <input type="" name="item_name" value="Enter YOUR twitch Username (optional)" class="form-control">
			</div>
		<% end %>
	Tip Message:
    <input type="" name="item_number" value="Short message to streamer (optional)" class="form-control">
    Amount:
    <input type="" name="amount" value="1.00" class="form-control">
    <input type="" name="currency_code" value="USD" class="form-control">

    <!-- Display the payment button. -->
    <input type="image" name="submit"
    src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif"
    alt="Donate">
    <img alt="" width="1" height="1"
    src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >

</form>
	</div>
	<div class="col-md-3">
		<div class="form-control">
			Words
		</div>
	</div>
	<% end %>
	<%# @streamlabs_response.read_body %>

	

	</div>